# Generated by Django 6.1 on 2026-08-15 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('SMARTPHONE', 'Smartphones & Tablets'), ('LAPTOP', 'Laptops & Computers'), ('GAMING', 'Gaming Consoles & Gear'), ('AUDIO', 'Audio & Wearables'), ('ACCESSORY', 'Accessories & Cables')], max_length=30)),
                ('brand', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('badge', models.CharField(blank=True, help_text='e.g. Hot, Refurbished, Best Seller, New', max_length=30)),
                ('specs', models.CharField(blank=True, help_text='Short bullet points separated by comma', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('in_stock', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=4.9, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date', '-appointment_time']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal tech notes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='device_model',
            field=models.CharField(default='General Device', help_text='e.g. iPhone 14 Pro, Dell XPS 15', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='issue_description',
            field=models.TextField(blank=True, help_text='Describe the issue or request'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='preferred_device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='wrench', help_text='Lucide/FontAwesome icon name', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='service',
            name='warranty_info',
            field=models.CharField(blank=True, default='90-Day Warranty included', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Customer notes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('CONFIRMED', 'Confirmed & Scheduled'), ('IN_PROGRESS', 'Repair / Service In Progress'), ('READY', 'Ready for Pickup'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('REPAIR', 'Hardware Repair'), ('CONSULTATION', 'Tech Consultation'), ('DEMO', 'Product Demo & Setup'), ('DIAGNOSTICS', 'Diagnostic Check'), ('UPGRADE', 'Hardware Upgrade & Custom PC')], default='REPAIR', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='scheduler.service'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
